import React from 'react';
import { View, Text, ScrollView, SafeAreaView } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { colors } from '../../theme/colors';
import { globalStyles } from '../../theme/styles';
import GlassCard from '../../components/GlassCard';
import ScreenHeader from '../../components/ScreenHeader';

const signals = [
  { time: '15:42', type: 'BUY', asset: 'BTC/USDT', price: '₹67,100', confidence: 91, reason: 'MA7 crossed MA21 with high volume' },
  { time: '14:30', type: 'HOLD', asset: 'ETH/USDT', price: '₹3,210', confidence: 76, reason: 'RSI neutral zone, wait for breakout' },
  { time: '13:15', type: 'SELL', asset: 'BNB/USDT', price: '₹412', confidence: 83, reason: 'Overbought RSI(82) + bearish divergence' },
  { time: '11:00', type: 'BUY', asset: 'SOL/USDT', price: '₹168', confidence: 88, reason: 'Bounced off MA50 with bullish candle' },
  { time: '09:20', type: 'SELL', asset: 'XRP/USDT', price: '₹0.58', confidence: 79, reason: 'Failed resistance at ₹0.60, volume drop' },
];

const sigColor = (t) => t === 'BUY' ? colors.success : t === 'SELL' ? colors.danger : colors.warning;

export default function AISignalsFeedScreen({ navigation }) {
  return (
    <SafeAreaView style={globalStyles.container}>
      <ScreenHeader title="AI Signals Feed" onBack={() => navigation.goBack()} />
      <ScrollView contentContainerStyle={globalStyles.scrollContent}>
        <GlassCard borderColor={colors.primary}>
          <Text style={globalStyles.cardLabel}>AI Trading Engine</Text>
          <Text style={{ color: colors.textPrimary, fontSize: 20, fontWeight: '800' }}>Real-Time Algo Signals</Text>
          <Text style={[globalStyles.cardCaption, { marginTop: 6 }]}>Generated by Moving Average Crossover + RSI + Volume analysis across top crypto pairs.</Text>
        </GlassCard>

        <Text style={globalStyles.sectionTitle}>Today's Signals</Text>
        {signals.map((s, i) => (
          <GlassCard key={i} style={{ marginBottom: 12 }} borderColor={sigColor(s.type) + '44'}>
            <View style={[globalStyles.row, { marginBottom: 10 }]}>
              <View style={[globalStyles.tag, { backgroundColor: sigColor(s.type) + '22' }]}>
                <Text style={[globalStyles.tagText, { color: sigColor(s.type) }]}>{s.type}</Text>
              </View>
              <Text style={globalStyles.cardCaption}>{s.time}</Text>
            </View>
            <View style={globalStyles.row}>
              <View>
                <Text style={{ color: colors.textPrimary, fontWeight: '700', fontSize: 16 }}>{s.asset}</Text>
                <Text style={[globalStyles.cardCaption, { marginTop: 3 }]}>{s.price}</Text>
              </View>
              <View style={{ alignItems: 'flex-end' }}>
                <Text style={{ color: sigColor(s.type), fontWeight: '800', fontSize: 18 }}>{s.confidence}%</Text>
                <Text style={globalStyles.cardCaption}>Confidence</Text>
              </View>
            </View>
            <View style={globalStyles.divider} />
            <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6 }}>
              <Ionicons name="bulb-outline" size={14} color={colors.textMuted} />
              <Text style={[globalStyles.cardCaption, { flex: 1 }]}>{s.reason}</Text>
            </View>
          </GlassCard>
        ))}
      </ScrollView>
    </SafeAreaView>
  );
}
